INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (1, 'Macarrão ao Molho Branco', 'Penne com champignons, tomates frescos e cortes de filet mignon. Refogado com um toque de vinho Chardonnay e black pepper', 59.90, 'https://www.demotivateur.fr/images/cover_recette/1602497794-shutterstock_1724358589.jpg', '/cardapio/comidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (2, 'Macarrão ao Molho Pesto', 'Penne com champignons, tomates frescos e cortes de filet mignon. Refogado com um toque de vinho Chardonnay e black pepper', 59.90, 'https://cdn.panelinha.com.br/receita/1564088181653-espaguete-ao-pesto.jpg', '/cardapio/comidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (3, 'Macarrão ao Molho Bolonhesa', 'Penne com champignons, tomates frescos e cortes de filet mignon. Refogado com um toque de vinho Chardonnay e black pepper', 69.90,'https://qul.imgix.net/45d6bd5e-5cc7-4b9a-b640-11a603027fee/426918_sld.jpg','/cardapio/comidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (4, 'Macarrão Cremoso com Legumes', 'Penne com champignons, tomates frescos e cortes de filet mignon. Refogado com um toque de vinho Chardonnay e black pepper', 45.90, 'https://i.pinimg.com/originals/82/49/52/824952c617fc0c1f0662447fe662a4df.jpg', '/cardapio/comidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (5, 'Coca-Cola', 'Refrigerante', 6.00, 'https://araujo.vteximg.com.br/arquivos/ids/4143343-1000-1000/07894900010015.jpg', '/cardapio/bebidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (6, 'Água', 'Sem gás', 4.00, 'https://images-americanas.b2w.io/produtos/01/00/img7/01/00/item/1588123/0/1588123027_1GG.jpg', '/cardapio/bebidas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (7, 'Petit Gateau', 'Chocolate', 7.50, 'https://pilotandofogao.com.br/wp-content/uploads/2020/08/Petit-Gateau.jpg', '/cardapio/sobremesas');
INSERT INTO CARDAPIO (ID, NOME, DESCRICAO, VALOR, IMAGEM, TIPO) VALUES (8, 'Red Velvet', 'Fatia de bolo', 14.00, 'https://s2.glbimg.com/2_tIB5GwIIikBFu4XVG8XT_d_DY=/0x0:690x570/600x0/smart/filters:gifv():strip_icc()/s2.glbimg.com/c-JZ7Rco02MLoZDbdjsxZoc5DXI%3D/s.glbimg.com/et/gs/f/original/2016/02/22/bolo_red_velvet.jpg', '/cardapio/sobremesas');
INSERT INTO USUARIO(ID, USER, SENHA, FUNCAO) VALUES (1, 'gerente', 'senha123', 'GERENTE'), (2, 'mesa1', '1', 'MESA');
